import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/ProductDashboard.module.css";
import { useState, useEffect } from "react";

const Products = () => {
  const [products, setProducts] = useState([]);
  const [categoryFilter, setCategoryFilter] = useState(null); //"Food", "Technology"
  //const [shouldReload, setShouldReload] = useState(true);
  const [newProduct, setNewProduct] = useState("");

  useEffect(() => {
    const getProducts = async () => {
      try {
        const url = categoryFilter
          ? `/api/products?category=${categoryFilter}`
          : "/api/products";
        const response = await fetch(url);
        if (response.ok) {
          const data = await response.json();
          setProducts(data);
        } else {
          throw new Error(
            `Fetch fehlgeschlagen mit Status: ${response.status}`
          );
        }
      } catch (error) {
        console.log(error);
        alert(error.message);
      }
      //setShouldReload(false)
    };
    //if (shouldReload) {
      getProducts();
  }, [categoryFilter]);

  async function deleteProduct(id) {
    try {
      const response = await fetch(`/api/products/${id}`, {method: "DELETE"})
      if (response.ok) {
        alert(`Product successfully deleted`);
        window.location.reload();
        //setShouldReload(true);
      } else {
        throw new Error(`Fetch fehlgeschlagen mit Status: ${response.status}`);
      }
  } catch (error) {
    alert(error.message);
  }
}

  async function addNewProduct(event) {
    event.preventDefault()
    const data = {
      name: event.target.name.value,
      category: event.target.category.value,
    };
    const endpoint = "api/products";
    const options = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    };
    const response = await fetch(endpoint, options);
    console.log(data);
    const result = await response.json();
    window.location.reload();
  }
  
  return (
    <>
      <Head>
        <title>Onkel Marcos Ramschladen - Produkte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="test">Onkel Marcos Ramschladen</h1>
        <p>Hier kannst du dir unsere Produkt-Kategorien ansehen:</p>
        <select
          onChange={(event) => {
            if (event.target.value === "all") {
              setCategoryFilter(null);
            } else {
              setCategoryFilter(event.target.value);
            }
          }}
        >
          <option value="all">Alle</option>
          <option value="Essen">Essen</option>
          <option value="Hi-Fi">Hi-Fi</option>
          <option value="Möbel">Möbel</option>
        </select>

        <h2>Unser Angebot in der Kategorie {categoryFilter}</h2>
        <p>Wähle dein Lieblingsprodukt aus:</p>

        <ul className={styles["product-list"]}>
          {products.map((product) => {
            return (
              <li key={product._id}>
                <Link href={`/products/${product._id}`}>{product.name}</Link>
                <button className={styles["product-button"]} onClick={() => deleteProduct(product._id)}>ENTFERNEN</button>
              </li>
            );
          })}
        </ul>

        <h2>Füge deine Produkte hinzu</h2>
        <p>Du suchst nach einem bestimmten Produkt aber es ist nicht dabei? Teile uns direkt im Forumular mit, um welches Produkt es geht!</p>

        <form onSubmit={(e) => addNewProduct(e)} className={styles["form"]}>
          <label htmlFor="name" className={styles["form-label"]}>Produkt</label>
          <input 
          type="text"
          name="name"
          id="name" 
          className={styles["form-input"]}></input>
          <label htmlFor="category" className={styles["form-label"]}>Kategorie</label>
          <input 
          type="text"
          name="category"
          id="category" 
          className={styles["form-input"]}></input>
          <button type="submit">Produkt hinzufügen</button>
        </form>
      </div>
    </>
  );
};

export default Products;
